-- Client Requests: clients submit requests / messages from their portal
-- (headcount requisition, process change, escalation, commendation, complaint
-- or feedback, commercial change, general) and AB BSS responds. Run these
-- THREE blocks one at a time in the Supabase SQL Editor.
--
-- SECURITY: unlike most tables in this app, these five have row level
-- security ON with NO policies, so the public (anon) key cannot read or write
-- them at all. Every read and write goes through the server routes
-- (app/api/client-portal/requests, app/api/client-requests/staff), which
-- verify the caller first -- the client's portal session, or the staff
-- member's Google sign-in token. Attachments live in the private
-- 'client-uploads' bucket.

-- ===== BLOCK 1 =====
create table public.client_requests (
  id uuid primary key default gen_random_uuid(),
  ref_no bigint generated by default as identity,
  client text not null,
  contact_id uuid references client_contacts(id) on delete set null,
  contact_name text,
  contact_email text,
  type text not null check (type in ('headcount', 'process_change', 'escalation', 'commendation', 'complaint_feedback', 'commercial_change', 'general')),
  subject text not null,
  details text not null,
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  send_to_level text not null check (send_to_level in ('team_lead', 'account_manager', 'director', 'ceo')),
  needed_by date,
  target_date date,
  effective_date date,
  status text not null default 'new' check (status in ('new', 'acknowledged', 'in_review', 'approved', 'declined', 'completed', 'closed')),
  requires_approval boolean not null default false,
  assigned_to text,
  approved_at timestamptz,
  closed_at timestamptz,
  staff_attention boolean not null default true,
  client_unread boolean not null default false,
  attachments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.client_request_messages (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references client_requests(id) on delete cascade,
  author_type text not null check (author_type in ('client', 'staff', 'system')),
  author_name text,
  author_email text,
  body text not null default '',
  visible_to_client boolean not null default true,
  attachments jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

-- ===== BLOCK 2 =====
create table public.client_request_approvals (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references client_requests(id) on delete cascade,
  approver_name text not null,
  approver_email text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'declined')),
  comment text,
  decided_at timestamptz,
  created_at timestamptz not null default now()
);
create table public.client_request_receivers (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references client_requests(id) on delete cascade,
  receiver_name text not null,
  receiver_email text not null,
  acknowledged_at timestamptz,
  created_at timestamptz not null default now()
);
create table public.client_comm_routing (
  id uuid primary key default gen_random_uuid(),
  client text,
  level text not null check (level in ('team_lead', 'account_manager', 'director', 'ceo')),
  recipients text not null,
  updated_by text,
  updated_at timestamptz not null default now()
);
create unique index client_comm_routing_unique on public.client_comm_routing (coalesce(lower(client), ''), level);

-- ===== BLOCK 3 : lock all five (no policies = no public access) =====
alter table public.client_requests enable row level security;
alter table public.client_request_messages enable row level security;
alter table public.client_request_approvals enable row level security;
alter table public.client_request_receivers enable row level security;
alter table public.client_comm_routing enable row level security;
